### PR TITLE
chore(workflow): Add release workflow

### PR DESCRIPTION
**Pull request by JuanVqz**
There is the following step before merging this proposal.

Generate a token in the RubyGems account (you can scope the token per gem or global) and add it to the repo under ombu_labs-auth > settings > secrets > actions > repository secrets with the following name RUBYGEMS_AUTH_TOKEN

image

### CODE REVIEW

**Review by etagwerker — COMMENTED** [review]
@JuanVqz Thanks for submitting this! I guess this is similar to https://www.fastruby.io/blog/gem/release/automate-the-gem-release-process.html?utm_source=Twitter&utm_medium=Tweet&utm_campaign=Rails&utm_term=gem&utm_content=how-to&utm_id=automate -- right? 

How does it work? Could you explain a little bit more about this release workflow? Does it only generate a release when there is a change to the version.rb file? 

Just trying to understand what would happen if we incorporated these changes to the gem... 

Thanks!

**Comment by JuanVqz** [comment]
hey @etagwerker yes, it is similar to that blog post.


we won't be required to change the version file manually anymore, the GA will update the `major-minor-patch` version for us according to the [commit message](https://www.conventionalcommits.org/en/v1.0.0/#summary).


Ie 1.
Currently we are in `v0.1.0`, let's think we merge a `dependabot` pr, it is bumping the `devise` gem version, by default, dependabot uses conventional commits, so, the PR's title is something like `chore(deps): Bump devise from x to x`, once we merged that pr the GA will run and will make a PR with a next patch version `v0.1.1`, you can think in `chore` means changing the `patch` version. but here we have something interesting the gem is not been released nor published at `v0.1.1` yet, it only created a pr with this title `chore(main): release 0.1.1`, it allows us to decide when to release and publish the next version (merging that pr).


Ie 2.

Let's think that we merge more than one pr.

Again, let's start with `v0.1.0`.

We merge a pr with title `chore(readme): fix a typo` it will create a pr suggesting release `v0.1.1` but we don't merge that pr, instead of that we merge another 2 prs with title `chore(ga): update ruby version` and `chore(rubocop): fix broken something cop`
this won't create 3 new release prs trying to resolve the 3 prs we already merged, what will happen is update the existing pr and add all the prs changes to the existing release pr. and will ended up adding the messages in the CHANGELOG.md automagically.

 Ie 3.
 
 What if we what to release a specific version like `v0.2.0-rc1`, and our current version is not consecutive because it's `v0.1.0`, we need to add a keyword `Release-As: 0.2.0-rc-1` in the pr's body and that will do the trick.
 
 I hope this answers your questions if not I have my DMs open :+1:

**Review by etagwerker — CHANGES_REQUESTED** [review]
@JuanVqz Thanks for explaining how this works! 

Now that I understand how it works, I believe we now need some form of documentation that explains how one needs to structure their commit messages based on the release workflow?

**Comment by JuanVqz** [comment]
> @JuanVqz Thanks for explaining how this works!
> 
> Now that I understand how it works, I believe we now need some form of documentation that explains how one needs to structure their commit messages based on the release workflow?

Remember that before merging this we should generate the token in the rubygems account where this gem is hosted and [add it to this repository](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) with the following name `RUBYGEMS_AUTH_TOKEN`.

**Review by etagwerker — APPROVED** [review]
@JuanVqz Great, thanks!

**Pull request merged**
